"""Generate bash snippet for per-worktree terminal background colors."""

from __future__ import annotations

from pathlib import Path

from emiglio_pm.manifest import Manifest


def generate_shell_init(manifest: Manifest, repo_root: Path) -> str:
    """Return a bash snippet that sets terminal bg color based on PWD.

    Uses OSC 11 to set background color and OSC 0 for terminal title.
    Emits a case statement keyed on "${PWD}/" so longer worktree paths
    match before the repo root. Tracks previous color to avoid redundant
    escape writes. Appends to PROMPT_COMMAND without clobbering.
    """
    repo = repo_root.resolve()
    wt_root = repo / manifest.project.worktree_root

    # Build path->color+port mapping; worktrees first (longer paths), then repo root
    entries: list[tuple[str, str, str, int]] = []
    for name, ws in manifest.workstreams.items():
        if ws.color or ws.port:
            wt_path = wt_root / name
            entries.append((str(wt_path), ws.color, name, ws.port))

    # Sort longest path first so worktrees match before repo root
    entries.sort(key=lambda e: len(e[0]), reverse=True)

    # Build case arms
    case_arms = []
    for path, color, name, port in entries:
        port_line = f'            _emiglio_port="{port}"\n' if port else ''
        case_arms.append(
            f'        {path}/*)\n'
            f'            _emiglio_bg="{color}"\n'
            f'            _emiglio_title="emiglio [{name}]"\n'
            f'{port_line}'
            f'            ;;'
        )

    # Repo root (develop branch)
    develop_color = manifest.project.develop_color
    develop_port = manifest.project.develop_port
    if develop_color or develop_port:
        port_line = f'            _emiglio_port="{develop_port}"\n' if develop_port else ''
        case_arms.append(
            f'        {repo}/*)\n'
            f'            _emiglio_bg="{develop_color}"\n'
            f'            _emiglio_title="emiglio [develop]"\n'
            f'{port_line}'
            f'            ;;'
        )

    # Default: reset
    case_arms.append(
        '        *)\n'
        '            _emiglio_bg="reset"\n'
        '            _emiglio_title=""\n'
        '            _emiglio_port=""\n'
        '            ;;'
    )

    case_block = "\n".join(case_arms)

    return f'''\
# emiglio-pm: per-worktree terminal background colors
# Generated by: emiglio-pm shell-init
# Regenerate with: uv run --project {repo} emiglio-pm shell-init

_emiglio_prev_bg=""

_emiglio_prompt_hook() {{
    local _emiglio_bg _emiglio_title _emiglio_port
    case "${{PWD}}/" in
{case_block}
    esac

    # Set background color only when it changes
    if [[ "$_emiglio_bg" != "$_emiglio_prev_bg" ]]; then
        if [[ "$_emiglio_bg" == "reset" ]]; then
            printf '\\e]111\\a'
            printf '\\e]0;\\a'
        else
            printf '\\e]11;%s\\a' "$_emiglio_bg"
            printf '\\e]0;%s\\a' "$_emiglio_title"
        fi
        _emiglio_prev_bg="$_emiglio_bg"
    fi

    # Export or unset EMIGLIO_WEB_PORT
    if [[ -n "$_emiglio_port" ]]; then
        export EMIGLIO_WEB_PORT="$_emiglio_port"
    else
        unset EMIGLIO_WEB_PORT
    fi
}}

# Append to PROMPT_COMMAND without clobbering
if [[ -z "$PROMPT_COMMAND" ]]; then
    PROMPT_COMMAND="_emiglio_prompt_hook"
elif [[ "$PROMPT_COMMAND" != *"_emiglio_prompt_hook"* ]]; then
    PROMPT_COMMAND="${{PROMPT_COMMAND%;}};_emiglio_prompt_hook"
fi
'''
